name = "flowsync-2"
main = "worker/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat_v2"]

[assets]
directory = "dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "flowsync"
database_id = "376955eb-a3f2-48c0-a8f2-056be5b1c9ea"
migrations_dir = "migrations_sqlite"

[vars]
OPENAI_BASE_URL = "https://open.bigmodel.cn/api/coding/paas/v4"
OPENAI_MODEL = "GLM-4.7"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
