name = "flowsync-2"
main = "worker/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat_v2"]

[assets]
directory = "dist"
binding = "ASSETS"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "165e16e1c93849e09e95097ed1c83141"

[vars]
OPENAI_BASE_URL = "https://open.bigmodel.cn/api/coding/paas/v4"
OPENAI_MODEL = "GLM-4.7"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
